# Generated by Django 5.0.2 on 2024-03-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingList', '0004_shoppinglistcategory_alter_shoppinglistitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ShoppingList.shoppinglistcategory'),
        ),
    ]
