# Generated by Django 5.0.2 on 2024-03-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_task_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(default='', max_length=255)),
                ('val', models.TextField(default='')),
                ('time', models.BigIntegerField(default=0)),
            ],
        ),
    ]
