# Generated by Django 5.0.2 on 2024-03-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='userid',
            field=models.BigIntegerField(default=0),
        ),
    ]
