from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from .models import ShoppingListItem, ShoppingListCategory

@receiver(post_save, sender=User)
def create_user_shopping_list(sender, instance, created, **kwargs):
    if created:
        roomEssentials = ShoppingListCategory.objects.get(name="Room Essentials")
        hygiene = ShoppingListCategory.objects.get(name="Hygiene")
        cleaningSupplies = ShoppingListCategory.objects.get(name="Cleaning Supplies")
        beachSupplies = ShoppingListCategory.objects.get(name="Beach Supplies")
        schoolSupplies = ShoppingListCategory.objects.get(name="School Supplies")
        emergencyPreparedness = ShoppingListCategory.objects.get(name="Emergency Preparedness")
        otherItems = ShoppingListCategory.objects.get(name="Other Items")
        ShoppingListItem.objects.create(user=instance, name="Twin XL bedding set", category=roomEssentials, url="https://www.amazon.com/s?k=twin+xl+sheet+sets").save()
        ShoppingListItem.objects.create(user=instance, name="Pillows", category=roomEssentials, url="https://www.amazon.com/s?k=bed+pillow")
        ShoppingListItem.objects.create(user=instance, name="Mattress pad", category=roomEssentials, url="https://www.amazon.com/s?k=mattress+pad")
        ShoppingListItem.objects.create(user=instance, name="Comforter and/or blanket", category=roomEssentials, url="https://www.amazon.com/s?k=comforter")
        ShoppingListItem.objects.create(user=instance, name="Alarm clock", category=roomEssentials, url="https://www.amazon.com/s?k=alarm+clock")
        ShoppingListItem.objects.create(user=instance, name="Lamp", category=roomEssentials, url="https://www.amazon.com/s?k=lamp")
        ShoppingListItem.objects.create(user=instance, name="Trash bin", category=roomEssentials, url="https://www.amazon.com/s?k=trash+bin")
        ShoppingListItem.objects.create(user=instance, name="Key chain that you would bet $148 on (price of a lost key)", category=roomEssentials, url="https://www.amazon.com/s?k=key+chain")
        ShoppingListItem.objects.create(user=instance, name="Clothes hangers", category=roomEssentials, url="clothes hangers")
        ShoppingListItem.objects.create(user=instance, name="Laundry basket", category=roomEssentials, url="https://www.amazon.com/s?k=laundry+basket")
        ShoppingListItem.objects.create(user=instance, name="Bath Towel", category=hygiene, url="https://www.amazon.com/s?kbath+towel")
        ShoppingListItem.objects.create(user=instance, name="Soap", category=hygiene, url="https://www.amazon.com/s?k=soap")
        ShoppingListItem.objects.create(user=instance, name="Shampoo and Conditioner", category=hygiene, url="https://www.amazon.com/s?k=shampoo+and+conditioner")
        ShoppingListItem.objects.create(user=instance, name="Deodorant", category=hygiene, url="https://www.amazon.com/s?k=deodorant")
        ShoppingListItem.objects.create(user=instance, name="Toothbrush and Toothpaste", category=hygiene, url="https://www.amazon.com/s?k=toothbrush+and+toothpaste")
        ShoppingListItem.objects.create(user=instance, name="Shaving supplies", category=hygiene, url="https://www.amazon.com/s?k=shaving+supplies")
        ShoppingListItem.objects.create(user=instance, name="Toilet Paper", category=hygiene, url="https://www.amazon.com/s?k=toilet+paper")
        ShoppingListItem.objects.create(user=instance, name="Dish Towel", category=cleaningSupplies, url="https://www.amazon.com/s?k=dish+towel")
        ShoppingListItem.objects.create(user=instance, name="Dish Soap", category=cleaningSupplies, url="https://www.amazon.com/s?k=dish+soap")
        ShoppingListItem.objects.create(user=instance, name="Room Deodorizing Spray", category=cleaningSupplies, url="https://www.amazon.com/s?k=room+deodorizing+spray")
        ShoppingListItem.objects.create(user=instance, name="Laundry Soap", category=cleaningSupplies, url="https://www.amazon.com/s?k=laundry+soap")
        ShoppingListItem.objects.create(user=instance, name="Disinfectant Wipes", category=cleaningSupplies, url="https://www.amazon.com/s?k=disinfectant+wipes")
        ShoppingListItem.objects.create(user=instance, name="Lysol Spray", category=cleaningSupplies, url="https://www.amazon.com/s?k=lysol+spray")
        ShoppingListItem.objects.create(user=instance, name="Swimsuit", category=beachSupplies, url="https://www.amazon.com/s?k=swimsuit")
        ShoppingListItem.objects.create(user=instance, name="Beach Towel", category=beachSupplies, url="https://www.amazon.com/s?k=beach+towel")
        ShoppingListItem.objects.create(user=instance, name="Sunscreen", category=beachSupplies, url="https://www.amazon.com/s?k=sunscreen")
        ShoppingListItem.objects.create(user=instance, name="Refillable Water Bottle", category=beachSupplies, url="https://www.amazon.com/s?k=refillable+water+bottle")
        ShoppingListItem.objects.create(user=instance, name="Personal Computer", category=schoolSupplies, url="https://www.amazon.com/s?k=personal+computer")
        ShoppingListItem.objects.create(user=instance, name="Printer", category=schoolSupplies, url="https://www.amazon.com/s?k=printer")
        ShoppingListItem.objects.create(user=instance, name="Printer Paper", category=schoolSupplies, url="https://www.amazon.com/s?k=printer+paper")
        ShoppingListItem.objects.create(user=instance, name="Ethernet Cable", category=schoolSupplies, url="https://www.amazon.com/s?k=ethernet+cable")
        ShoppingListItem.objects.create(user=instance, name="Flash Drive", category=schoolSupplies, url="https://www.amazon.com/s?k=flash+drive")
        ShoppingListItem.objects.create(user=instance, name="Notebooks", category=schoolSupplies, url="https://www.amazon.com/s?k=notebooks")
        ShoppingListItem.objects.create(user=instance, name="Laptop Lock", category=schoolSupplies, url="https://www.amazon.com/s?k=laptop+lock")
        ShoppingListItem.objects.create(user=instance, name="Office Supplies (Poster Putty, Stapler, Push Pins, Pen/Pencils, Envelopes and Stamps)", category=schoolSupplies, url="https://www.amazon.com/s?k=office+supplies")
        ShoppingListItem.objects.create(user=instance, name="Desk Lamp", category=schoolSupplies, url="https://www.amazon.com/s?k=desk+lamp")
        ShoppingListItem.objects.create(user=instance, name="Power Strip with Surge Protector", category=schoolSupplies, url="https://www.amazon.com/s?k=power+strip+with+surge+protector")
        ShoppingListItem.objects.create(user=instance, name="Multi-port USB Charger", category=schoolSupplies, url="https://www.amazon.com/s?k=multi-port+usb+charger")
        ShoppingListItem.objects.create(user=instance, name="Headset", category=schoolSupplies, url="https://www.amazon.com/s?k=headset")
        ShoppingListItem.objects.create(user=instance, name="Flashlight", category=emergencyPreparedness, url="https://www.amazon.com/s?k=flashlight")
        ShoppingListItem.objects.create(user=instance, name="Batteries", category=emergencyPreparedness, url="https://www.amazon.com/s?k=batteries")
        ShoppingListItem.objects.create(user=instance, name="First-aid Kit", category=emergencyPreparedness, url="https://www.amazon.com/s?k=first-aid+kit")
        ShoppingListItem.objects.create(user=instance, name="Fan", category=otherItems, url="https://www.amazon.com/s?k=fan")
        ShoppingListItem.objects.create(user=instance, name="Umbrella", category=otherItems, url="https://www.amazon.com/s?k=umbrella")
        ShoppingListItem.objects.create(user=instance, name="Ear Plugs", category=otherItems, url="https://www.amazon.com/s?k=ear+plugs")
        ShoppingListItem.objects.create(user=instance, name="Small Sewing Kit", category=otherItems, url="https://www.amazon.com/s?k=sewing+kit")
        ShoppingListItem.objects.create(user=instance, name="Small Tool Kit", category=otherItems, url="https://www.amazon.com/s?k=tool+kit")
        ShoppingListItem.objects.create(user=instance, name="Storage Bins", category=otherItems, url="https://www.amazon.com/s?k=storage+bins")
        ShoppingListItem.objects.create(user=instance, name="Dishes and Utensils", category=otherItems, url="https://www.amazon.com/s?k=dishes+and+utensils")
        ShoppingListItem.objects.create(user=instance, name="Camera", category=otherItems, url="https://www.amazon.com/s?k=camera")
        ShoppingListItem.objects.create(user=instance, name="Can Opener", category=otherItems, url="https://www.amazon.com/s?k=can+opener")
        