# Generated by Django 5.0.2 on 2024-03-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
