# Generated by Django 5.0.2 on 2024-03-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_student',
            field=models.BooleanField(default=True),
        ),
    ]
