# Generated by Django 5.0.2 on 2024-03-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_student',
            field=models.BooleanField(default=False),
        ),
    ]
