# Generated by Django 5.0.2 on 2024-03-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
