# Generated by Django 5.0.2 on 2024-03-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboard', '0002_checklist_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='task10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='task6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='task7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='task8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='task9',
            field=models.BooleanField(default=False),
        ),
    ]
