# Generated by Django 5.0.2 on 2024-03-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovoTaskNinja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
