# Generated by Django 5.0.2 on 2024-03-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovoTaskNinja', '0003_delete_shoppinglist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatroom',
        ),
        migrations.RemoveField(
            model_name='cycrequirement',
            name='completedByCourse',
        ),
        migrations.RemoveField(
            model_name='inprogresscourse',
            name='task',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompletedCourse',
        ),
        migrations.DeleteModel(
            name='CYCRequirement',
        ),
        migrations.DeleteModel(
            name='InProgressCourse',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
