# Generated by Django 5.0.2 on 2024-03-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovoTaskNinja', '0009_profile_graduation_year_profile_highschool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='homestate',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
