# Generated by Django 5.0.2 on 2024-03-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovoTaskNinja', '0011_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='user',
        ),
    ]
